import React, { useState } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const ExportButton = ({ analysisResult }) => {
  const [exporting, setExporting] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  const exportAsJSON = () => {
    const dataStr = JSON.stringify(analysisResult, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `gitgrade-${analysisResult.repoInfo?.owner}-${analysisResult.repoInfo?.name}-${Date.now()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setShowMenu(false);
  };

  const exportAsPDF = async () => {
    try {
      setExporting(true);
      setShowMenu(false);
      
      // Create a temporary container for the report
      const reportElement = document.getElementById('results');
      if (!reportElement) {
        throw new Error('Report element not found');
      }

      // Use html2canvas to capture the content
      const canvas = await html2canvas(reportElement, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff'
      });

      const imgWidth = 210; // A4 width in mm
      const pageHeight = 297; // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;

      const pdf = new jsPDF('p', 'mm', 'a4');
      let position = 0;

      // Add first page
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      // Add additional pages if needed
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`gitgrade-${analysisResult.repoInfo?.owner}-${analysisResult.repoInfo?.name}-${Date.now()}.pdf`);
    } catch (error) {
      console.error('PDF export failed:', error);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  const exportAsMarkdown = () => {
    const { score, rating, badge, summary, repoInfo, metrics, roadmap } = analysisResult;
    
    let markdown = `# GitGrade Analysis Report\n\n`;
    markdown += `**Repository:** ${repoInfo?.owner}/${repoInfo?.name}\n`;
    markdown += `**Analysis Date:** ${new Date().toLocaleDateString()}\n\n`;
    
    markdown += `## Overall Score\n\n`;
    markdown += `**Score:** ${score}/900\n`;
    markdown += `**Rating:** ${rating}\n`;
    markdown += `**Badge:** ${badge}\n\n`;
    
    markdown += `## Summary\n\n${summary}\n\n`;
    
    markdown += `## Metrics Breakdown\n\n`;
    metrics.forEach(metric => {
      markdown += `### ${metric.category}\n`;
      markdown += `- **Score:** ${metric.score}/${metric.max_score}\n`;
      markdown += `- **Weight:** ${metric.weight}%\n`;
      markdown += `- **Status:** ${metric.status}\n\n`;
    });
    
    markdown += `## Improvement Roadmap\n\n`;
    roadmap.forEach((item, index) => {
      markdown += `### ${index + 1}. ${item.title}\n`;
      markdown += `**Priority:** ${item.priority} | **Effort:** ${item.effort} | **Impact:** ${item.impact}\n\n`;
      markdown += `${item.description}\n\n`;
      if (item.tasks && item.tasks.length > 0) {
        markdown += `**Tasks:**\n`;
        item.tasks.forEach(task => {
          markdown += `- ${task}\n`;
        });
        markdown += `\n`;
      }
    });
    
    markdown += `---\n\n`;
    markdown += `*Generated by GitGrade - AI-Powered Repository Analyzer*\n`;
    
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `gitgrade-${repoInfo?.owner}-${repoInfo?.name}-${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setShowMenu(false);
  };

  return (
    <div className="relative inline-block">
      <button
        onClick={() => setShowMenu(!showMenu)}
        disabled={exporting}
        className="btn bg-gradient-to-r from-primary-600 to-purple-600 text-white hover:from-primary-700 hover:to-purple-700 disabled:opacity-50 flex items-center gap-2"
      >
        {exporting ? (
          <>
            <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent"></div>
            Exporting...
          </>
        ) : (
          <>
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download Report
          </>
        )}
      </button>

      {showMenu && (
        <>
          <div 
            className="fixed inset-0 z-10" 
            onClick={() => setShowMenu(false)}
          ></div>
          <div className="absolute right-0 mt-2 w-56 bg-white rounded-lg shadow-lg border border-gray-200 z-20 overflow-hidden">
            <button
              onClick={exportAsPDF}
              className="w-full px-4 py-3 text-left hover:bg-gray-50 flex items-center gap-3 transition"
            >
              <svg className="w-5 h-5 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
              </svg>
              <div>
                <div className="font-medium text-gray-900">Export as PDF</div>
                <div className="text-xs text-gray-500">High-quality document</div>
              </div>
            </button>

            <button
              onClick={exportAsJSON}
              className="w-full px-4 py-3 text-left hover:bg-gray-50 flex items-center gap-3 transition border-t border-gray-100"
            >
              <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
              <div>
                <div className="font-medium text-gray-900">Export as JSON</div>
                <div className="text-xs text-gray-500">Machine-readable data</div>
              </div>
            </button>

            <button
              onClick={exportAsMarkdown}
              className="w-full px-4 py-3 text-left hover:bg-gray-50 flex items-center gap-3 transition border-t border-gray-100"
            >
              <svg className="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <div>
                <div className="font-medium text-gray-900">Export as Markdown</div>
                <div className="text-xs text-gray-500">Documentation format</div>
              </div>
            </button>
          </div>
        </>
      )}
    </div>
  );
};

export default ExportButton;
